In [1]:
import numpy as np
import pandas as pd 
import sys
sys.path.append('..')


In [2]:
_mean_gamma =  2.5
_std_gamma =  1.5

_gamma_alpha = (_mean_gamma / _std_gamma) ** 2
_gamma_beta = _mean_gamma / _std_gamma ** 2


In [3]:
SEED = 1  # 3438  ##
np.random.seed(SEED)
    
_ARRIVAL_MEANS = np.random.gamma(_gamma_alpha, 1 / _gamma_beta, size=(8, 15)).astype(int)

In [4]:
_ARRIVAL_MEANS

array([[5, 1, 1, 1, 5, 1, 4, 0, 4, 0, 1, 1, 0, 4, 3],
       [1, 1, 3, 1, 1, 0, 2, 1, 1, 2, 1, 2, 3, 2, 1],
       [1, 3, 2, 3, 3, 1, 4, 5, 6, 0, 2, 3, 2, 0, 2],
       [3, 1, 1, 2, 2, 2, 4, 1, 1, 1, 2, 1, 4, 0, 2],
       [3, 1, 0, 2, 2, 0, 2, 0, 2, 1, 0, 4, 0, 3, 0],
       [3, 3, 1, 3, 2, 3, 3, 3, 2, 2, 3, 4, 6, 2, 2],
       [2, 0, 1, 1, 2, 1, 6, 0, 8, 1, 4, 1, 0, 2, 2],
       [1, 2, 2, 6, 4, 3, 2, 1, 3, 0, 0, 0, 6, 1, 0]])

In [5]:

# _ARRIVAL_MEANS[[1, 2, 5, 6], :] = 0 # oorignal experiments
# _ARRIVAL_MEANS[[0, 3, 6, 7], :] = 0
# _ARRIVAL_MEANS[:, [2, 3, 4, 9, 10, 11]] = 0
 
_ARRIVAL_MEANS 

array([[5, 1, 1, 1, 5, 1, 4, 0, 4, 0, 1, 1, 0, 4, 3],
       [1, 1, 3, 1, 1, 0, 2, 1, 1, 2, 1, 2, 3, 2, 1],
       [1, 3, 2, 3, 3, 1, 4, 5, 6, 0, 2, 3, 2, 0, 2],
       [3, 1, 1, 2, 2, 2, 4, 1, 1, 1, 2, 1, 4, 0, 2],
       [3, 1, 0, 2, 2, 0, 2, 0, 2, 1, 0, 4, 0, 3, 0],
       [3, 3, 1, 3, 2, 3, 3, 3, 2, 2, 3, 4, 6, 2, 2],
       [2, 0, 1, 1, 2, 1, 6, 0, 8, 1, 4, 1, 0, 2, 2],
       [1, 2, 2, 6, 4, 3, 2, 1, 3, 0, 0, 0, 6, 1, 0]])

In [6]:
fname = '../stops/arrival_means'
np.save(fname, _ARRIVAL_MEANS)


In [7]:
np.load(fname + '.npy')

array([[5, 1, 1, 1, 5, 1, 4, 0, 4, 0, 1, 1, 0, 4, 3],
       [1, 1, 3, 1, 1, 0, 2, 1, 1, 2, 1, 2, 3, 2, 1],
       [1, 3, 2, 3, 3, 1, 4, 5, 6, 0, 2, 3, 2, 0, 2],
       [3, 1, 1, 2, 2, 2, 4, 1, 1, 1, 2, 1, 4, 0, 2],
       [3, 1, 0, 2, 2, 0, 2, 0, 2, 1, 0, 4, 0, 3, 0],
       [3, 3, 1, 3, 2, 3, 3, 3, 2, 2, 3, 4, 6, 2, 2],
       [2, 0, 1, 1, 2, 1, 6, 0, 8, 1, 4, 1, 0, 2, 2],
       [1, 2, 2, 6, 4, 3, 2, 1, 3, 0, 0, 0, 6, 1, 0]])

In [8]:
df = pd.DataFrame(_ARRIVAL_MEANS)

In [9]:
df

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
0   5   1   1   1   5   1   4   0   4   0   1   1   0   4   3
1   1   1   3   1   1   0   2   1   1   2   1   2   3   2   1
2   1   3   2   3   3   1   4   5   6   0   2   3   2   0   2
3   3   1   1   2   2   2   4   1   1   1   2   1   4   0   2
4   3   1   0   2   2   0   2   0   2   1   0   4   0   3   0
5   3   3   1   3   2   3   3   3   2   2   3   4   6   2   2
6   2   0   1   1   2   1   6   0   8   1   4   1   0   2   2
7   1   2   2   6   4   3   2   1   3   0   0   0   6   1   0

In [10]:
print(df.to_latex())

\begin{tabular}{lrrrrrrrrrrrrrrr}
\toprule
{} &  0  &  1  &  2  &  3  &  4  &  5  &  6  &  7  &  8  &  9  &  10 &  11 &  12 &  13 &  14 \\
\midrule
0 &   5 &   1 &   1 &   1 &   5 &   1 &   4 &   0 &   4 &   0 &   1 &   1 &   0 &   4 &   3 \\
1 &   1 &   1 &   3 &   1 &   1 &   0 &   2 &   1 &   1 &   2 &   1 &   2 &   3 &   2 &   1 \\
2 &   1 &   3 &   2 &   3 &   3 &   1 &   4 &   5 &   6 &   0 &   2 &   3 &   2 &   0 &   2 \\
3 &   3 &   1 &   1 &   2 &   2 &   2 &   4 &   1 &   1 &   1 &   2 &   1 &   4 &   0 &   2 \\
4 &   3 &   1 &   0 &   2 &   2 &   0 &   2 &   0 &   2 &   1 &   0 &   4 &   0 &   3 &   0 \\
5 &   3 &   3 &   1 &   3 &   2 &   3 &   3 &   3 &   2 &   2 &   3 &   4 &   6 &   2 &   2 \\
6 &   2 &   0 &   1 &   1 &   2 &   1 &   6 &   0 &   8 &   1 &   4 &   1 &   0 &   2 &   2 \\
7 &   1 &   2 &   2 &   6 &   4 &   3 &   2 &   1 &   3 &   0 &   0 &   0 &   6 &   1 &   0 \\
\bottomrule
\end{tabular}

